In [17]:
import pandas as pd
a8=pd.read_csv(r"d:\iris.csv")
df8=a8[['v1','v2','v3','v4']].values

In [18]:
import pandas as pd
aa=pd.read_csv(r"d:\USArrests_data.csv")
df2=aa[['Murder','Assault','UrbanPop','Rape']]
df5 = df2.values

In [19]:
import pandas as pd
a1=pd.read_csv(r"d:\protein.csv")
df6=a1[['v1','v2','v3','v4','v5','v6','v7','v8','v9',]].values
#print(df6)


In [20]:
import pandas as pd
aa=pd.read_csv(r"d:\judge.csv")
#df2=aa[['Murder','Assault','UrbanPop','Rape']]
df5 = aa.values


In [21]:
import pandas as pd
a7=pd.read_csv(r"d:\JudgeRatings.csv")
df7=a7[['v1','v2','v3','v4','v5','v6','v7','v8','v9','v10','v11','v12']].values
#print(df7)

 ##### Lloyd Algorithm    ############

In [2]:
                   ##### Lloyd Algorithm    ############
import time
import numpy as np

def lloyd_kmeans(X, n_clusters, max_iters=200, tol=1e-4):

    start_time = time.time()

    # اختيار مراكز العناقيد الأولية بشكل عشوائي
    centers = X[np.random.choice(len(X), n_clusters, replace=False)]
    #print(centers)
    
    # مجموع مربعات الأخطاء (SSE)
    sse = 0.0 
 
    for iter in range(max_iters):
        # حساب المسافات بين كل نقطة وكل مركز
        distances = np.linalg.norm(X[:, np.newaxis] - centers, axis=2)
       
        # تصنيف كل نقطة إلى أقرب مركز
        labels = np.argmin(distances, axis=1)
                
        # حفظ مراكز العناقيد الحالية للمقارنة بعد التحديث
        old_centers = np.copy(centers)       
        
        # تحديث مراكز العناقيد
        for i in range(n_clusters):
            cluster_points = X[labels == i]
            if len(cluster_points) > 0:
                centers[i] = cluster_points.mean(axis=0)
        # حساب مجموع مربعات الأخطاء (SSE)
        sse = np.sum(np.min(distances, axis=1)**2)
        # التحقق مما إذا كانت مراكز العناقيد لم تعد تتغير بشكل كبير
        if np.allclose(old_centers, centers, atol=tol):
            break
        sse = np.sum(np.min(distances, axis=1)**2)
        
    end_time = time.time()
    execution_time = end_time - start_time
    # تقسيم الوقت إلى أجزاء
    seconds = int(execution_time)
    milliseconds = (execution_time - seconds) * 1000
    microseconds = (milliseconds - int(milliseconds)) * 1000

    print(f"Execution time: {seconds} seconds, {int(milliseconds)} milliseconds, {int(microseconds)} microseconds")

    print(f"Execution time: {execution_time} seconds")

    return centers, labels, sse

In [5]:
###  Lloyd 
print("Lloyd Algorthim")
X = df7
n_clusters = 4
np.random.seed(8)
centers, labels,sse = lloyd_kmeans(X, n_clusters)
print("مراكز العناقيد النهائية:")
print(centers)
print("تصنيف النقاط:")
print(labels)
print("SSE:")
print(sse)

Lloyd Algorthim
Execution time: 0 seconds, 4 milliseconds, 987 microseconds
Execution time: 0.004987239837646484 seconds
مراكز العناقيد النهائية:
[[7.75555556 6.91111111 5.77777778 6.42222222 6.22222222 6.42222222
  6.08888889 6.11111111 5.73333333 5.92222222 6.51111111 5.85555556]
 [7.8        7.86363636 7.32727273 7.80909091 7.67272727 7.70909091
  7.54545455 7.53636364 7.31818182 7.42727273 8.09090909 7.64545455]
 [6.52857143 8.17142857 7.8        7.32857143 7.12857143 7.17142857
  7.12857143 7.18571429 7.12857143 7.17142857 7.92857143 7.57142857]
 [7.40625    8.6875     8.5        8.4875     8.20625    8.28125
  8.3375     8.3625     8.225      8.26875    8.63125    8.56875   ]]
تصنيف النقاط:
[2 3 1 3 0 3 3 0 3 1 2 2 2 0 3 1 0 1 1 0 2 0 0 2 3 3 3 3 3 3 1 1 3 3 0 3 1
 2 1 1 0 3 1]
SSE:
116.71000180375182


## MacQueen

In [868]:
import numpy as np

def MacQueen_kmeans(data, k, max_iterations=50):
    centers = data[np.random.choice(range(len(data)), k, replace=False)]
    #print(centers)
    labels= np.full(len(data), 999)    
    prev_centers = np.copy(centers)
    sse=0.0
    
    for iter in range(max_iterations):
        for i in range(len(data)):
            point = data[i]
            distances = np.linalg.norm(point - centers, axis=1)
            cluster_index = np.argmin(distances)
            labels[i] = cluster_index
            
            for j in range(k):
                cluster_points = data[labels == j]
                if len(cluster_points) > 0:
                    centers[j] = cluster_points.mean(axis=0)
        
        if np.all(centers == prev_centers):
            break
        
        distances = np.linalg.norm(data[:, np.newaxis] - centers, axis=2)
        sse = np.sum(np.min(distances, axis=1)**2)
        prev_centers = np.copy(centers)   
    return labels, centers,sse
  

In [869]:
### MacQueen 
print("MacQueen Algorthim")
# قم بتحميل البيانات الخاصة بك
data =df5
#np.random.seed(55)
# تحديد عد العناقيد
k = 5

# تنفيذ خوارزمية K-means
labels, centers,sse= MacQueen_kmeans(data, k)
print("Labels:", labels)
#print("Centers:", centers)
print("sse:", sse)



MacQueen Algorthim
Labels: [1 1 0 2 1 2 3 1 0 2 4 3 1 3 4 3 3 1 4 0 3 1 4 1 2 3 3 1 4 3 0 1 0 4 3 3 3
 3 2 1 4 2 2 3 4 3 3 4 4 3]
sse: 26684.554397249805


### الطريقتين معا

In [611]:
###  Lloyd 
z=3
print("Lloyd Algorthim")
X = df5
n_clusters = 4
np.random.seed(z)
centers, labels,sse = lloyd_kmeans(X, n_clusters)
print("مراكز العناقيد النهائية:")
#print(centers)
print("تصنيف النقاط:")
print(labels)
print("SSE:")
print(sse)

print("")
print("")
print("")

###  MacQueen 
print("MacQueen Algorthim")
# قم بتحميل البيانات الخاصة بك
data =df5
np.random.seed(z)
# تحديد عد العناقيد
k = 4

# تنفيذ خوارزمية K-means
labels, centers,sse= MacQueen_kmeans(data, k)
print("Labels:", labels)
#print("Centers:", centers)
print("sse:", sse)


###  my 
print("my Algorthim")
data= df5
k = 4
np.random.seed(z)
centers, labels,sse = My_kmeans(data, k)
print("مراكز العناقيد النهائية:")
print(centers)
print("تصنيف النقاط:")
print(labels)
# print("SSE:")
print(sse)


Lloyd Algorthim
[[ 10.4 249.   83.   24. ]
 [ 14.4 279.   48.   22.5]
 [ 17.4 211.   60.   25.8]
 [  5.7  81.   39.    9.3]]
مراكز العناقيد النهائية:
تصنيف النقاط:
[0 0 1 2 0 2 3 0 1 2 3 3 0 3 3 3 3 0 3 1 2 0 3 0 2 3 3 0 3 2 1 0 1 3 3 2 2
 3 2 1 3 2 2 3 3 2 2 3 3 2]
SSE:
37735.02419047619



MacQueen Algorthim
[[ 10.4 249.   83.   24. ]
 [ 14.4 279.   48.   22.5]
 [ 17.4 211.   60.   25.8]
 [  5.7  81.   39.    9.3]]
Labels: [1 1 0 2 1 2 3 1 0 2 3 3 1 3 3 3 3 1 3 0 2 1 3 1 2 3 3 1 3 2 0 1 0 3 3 2 2
 3 2 1 3 2 2 3 3 2 2 3 3 2]
sse: 37659.21922077922
my Algorthim
مراكز العناقيد النهائية:
[0 1 1 2 0 2 3 0 1 2 3 3 0 3 3 3 3 0 3 1 2 0 3 1 2 3 3 0 3 2 1 0 1 3 3 2 2
 3 2 1 3 2 2 3 3 2 2 3 3 2]
تصنيف النقاط:
[[ 11.1625     251.125       76.375       28.875     ]
 [ 12.4625     294.          60.25        27.875     ]
 [  8.21428571 173.28571429  70.64285714  22.84285714]
 [  4.27        87.55        59.75        14.39      ]]
39013.30285714286


In [170]:
###  Lloyd 
print("Lloyd Algorthim")
X = df5
n_clusters = 4
np.random.seed(0)
centers, labels,sse = lloyd_kmeans(X, n_clusters)
print("centers og Llloyd is ")
print(centers)
print(sse)
print(labels)
###  my 
print("my Algorthim")
data= df5
k = 4
#np.random.seed(0)
centers, labels,sse = My_kmeans(data, k)
print("مراكز العناقيد النهائية:")
print(centers)
print("تصنيف النقاط:")
print(labels)
# print("SSE:")
print(sse)


Lloyd Algorthim
[[  2.1  57.   56.    9.5]
 [  2.6 120.   54.   14.2]
 [  5.3  46.   83.   20.2]
 [ 13.2 188.   59.   26.9]]
centers og Llloyd is 
[[  2.68888889  64.55555556  50.66666667  10.54444444]
 [  6.32857143 139.71428571  67.95238095  19.16666667]
 [  5.3         46.          83.          20.2       ]
 [ 11.94736842 261.94736842  69.          28.63157895]]
55082.07674185464
[3 3 3 1 3 3 1 3 3 3 2 1 3 1 0 1 1 3 0 3 1 3 0 3 1 1 1 3 0 1 3 3 3 0 1 1 1
 1 1 3 0 1 3 1 0 1 1 0 0 1]
my Algorthim
مراكز العناقيد النهائية:
[1 1 0 2 1 2 3 1 0 2 3 3 1 3 3 3 3 1 3 0 2 1 3 1 2 3 3 1 3 2 1 1 0 3 3 2 2
 3 2 1 3 2 2 3 3 2 2 3 3 2]
تصنيف النقاط:
[[ 11.95       316.5         68.          26.7       ]
 [ 11.76666667 257.91666667  68.41666667  28.93333333]
 [  8.21428571 173.28571429  70.64285714  22.84285714]
 [  4.27        87.55        59.75        14.39      ]]
37652.659523809525


### الخوارزمية المقترحة I 

### Hartigan Method

#### 

 code Hartigan

In [941]:
import numpy as np

def Hartigan_kmeans(data, k, max_iterations=20):
    centers = data[np.random.choice(range(len(data)), k, replace=False)]
    #print(centers)
    labels= np.full(len(data), 0) 
    
    best_labels = None
    best_sse = np.inf
    prev_centers = np.copy(centers)
    sse=0
    for iter in range(max_iterations):  # التكرار حتى يتوقف أو يتحقق الشرط
        for i in range(len(data)):  # اختيار النقطة أو الحالة
            point = data[i]
            sses = []
            #print (iter+1,i+1)
            # نقل النقطة إلى كل عنقود وحساب SSE
            for j in range(k):
                labels[i] = j
                # حساب مراكز العناقيد الحالية
                for c in range(k):
                    cluster_points = data[labels == c]
                    if len(cluster_points) > 0:
                        centers[c] = cluster_points.mean(axis=0)
                
                # حساب SSE لهذا التصنيف
                current_sse = 0.0
                for c in range(k):
                    cluster_points = data[labels == c]
                    #print(cluster_points)
                    if len(cluster_points) > 0:
                        cluster_center = np.mean(cluster_points, axis=0)
                        current_sse += np.sum(np.linalg.norm(cluster_points - cluster_center, axis=1) ** 2)
                
                sses.append(current_sse)
                
                           
            # اختيار أفضل تصنيف بناءً على أدنى قيمة SSE
            min_sse_index = np.argmin(sses)
            labels[i] = min_sse_index
            current_best_sse = sses[min_sse_index]
            #print(sses)
            # مقارنة أفضل قيمة SSE مع أفضل قيمة SSE محدثة
            if current_best_sse < best_sse:
                best_sse = current_best_sse
            best_labels = np.copy(labels)
                                      
                # تحديث مراكز العناقيد بعد تحديث التصنيف
            for c in range(k):
                    cluster_points = data[labels == c]
                    if len(cluster_points) > 0:
                        centers[c] = cluster_points.mean(axis=0)
        if np.all(centers == prev_centers):
            break 
        # distances = np.linalg.norm(data[:, np.newaxis] - centers, axis=2)
        # sse = np.sum(np.min(distances, axis=1)**2)
        prev_centers = np.copy(centers)
    #print(sse)
    return best_labels, centers, best_sse



In [942]:
print("Hartigan Algorthim")
data= df5
k = 4
for i in range(10):
    np.random.seed(i)
    best_labels, centers, best_sse = Hartigan_kmeans(data, k)
    #print("مراكز العناقيد النهائية:")
    #print(centers)
    # print("تصنيف النقاط:")
#print(best_labels)
    #print("SSE:")
    print(best_sse)
#np.random.seed(101)
# best_labels, centers, best_sse = Hartigan_kmeans(data, k)
#     #print("مراكز العناقيد النهائية:")
# #print(centers)
#     # print("تصنيف النقاط:")
# #print(best_labels)
#     #print("SSE:")
# print(best_sse)


Hartigan Algorthim
37652.659523809525
37652.659523809525
37652.659523809525
37652.659523809525
37652.659523809525
37652.659523809525
37652.659523809525
37652.659523809525
37652.659523809525
37652.659523809525


In [830]:
np.random.seed(1)
labels,centers, sse = My_kmeans(data, k)
print("مراكز العناقيد النهائية:")
print(centers)
print("تصنيف النقاط:")
print(labels)
print("SSE:")
print(sse)

مراكز العناقيد النهائية:
[[ 11.8125     272.5625      68.3125      28.375     ]
 [  5.59       112.4         65.6         17.27      ]
 [  2.95        62.7         53.9         11.51      ]
 [  8.21428571 173.28571429  70.64285714  22.84285714]]
تصنيف النقاط:
[0 0 0 3 0 3 1 0 0 3 2 1 0 1 2 1 1 0 2 0 3 0 2 0 3 1 1 0 2 3 0 0 0 2 1 3 3
 1 3 0 2 3 3 1 2 3 3 2 2 3]
SSE:
34728.629357142854


# خوارزمية 2   بدون التعديلات

In [1440]:
import numpy as np
def My_kmeans(data, k, max_iterations=100):
    
    centers= data[np.random.choice(range(len(data)), k, replace=False)]
    #print(centers)
    labels=np.full(len(data), 999)  
    prev_centers = np.copy(centers)
    sse=0.0
      
    for iter in range(max_iterations):  
        for i in range(len(data)):              
            point = data[i]
            distances = np.linalg.norm(point - centers, axis=1)
            cluster_index = np.argmin(distances)
            dist_to_nearest_cluster = distances[cluster_index]

            if (labels[i]==cluster_index):  
                sorted_distances_indices = np.argsort(distances)                
                second_nearest_cluster_index = sorted_distances_indices[1]
                dist_to_second_nearest_cluster = distances[second_nearest_cluster_index]
                           
                num_points_in_nearest_cluster = np.sum(labels == cluster_index)
                if num_points_in_nearest_cluster > 1:
                    D = (dist_to_nearest_cluster ) / (num_points_in_nearest_cluster - 1) + dist_to_nearest_cluster
                else:
                    D = dist_to_nearest_cluster                
                E = dist_to_second_nearest_cluster
                if E < D:
                    labels[i] = second_nearest_cluster_index                   
            else:
                labels[i]=cluster_index                
            for j in range(k): 
                            cluster_points = data[labels == j]   
                            if len(cluster_points) > 0:
                               centers[j] = cluster_points.mean(axis=0)  
                           
        if np.all(centers == prev_centers):
            break
        
        distances = np.linalg.norm(data[:, np.newaxis] - centers, axis=2)
        sse = np.sum(np.min(distances, axis=1)**2)
        
        prev_centers = np.copy(centers) 
    print(labels_1)
    print(centers_1)
    return labels, centers, sse



In [1504]:
data=df8
labels,centers, sse = My_kmeans(data, k)
print(sse)
#print(centers)
#print(labels)
#print(centers_1)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 2 3 2 3 2 3 2 2 2 2 3 2 3 2 2 3 2 3 2 3 3
 3 3 3 3 3 2 2 2 2 3 2 3 3 3 2 2 2 3 2 2 2 2 2 3 2 2 0 3 0 0 0 0 2 0 0 0 3
 3 0 3 3 0 0 0 0 3 0 3 0 3 0 0 3 3 0 0 0 0 0 3 3 0 0 0 3 0 0 0 3 0 0 0 3 3
 0 3]
[[6.9125     3.1        5.846875   2.13125   ]
 [5.006      3.428      1.462      0.246     ]
 [5.53214286 2.63571429 3.96071429 1.22857143]
 [6.2525     2.855      4.815      1.625     ]]
71.44524662095121


In [1359]:
labels_1,centers_1 = My2_kmeans(data, k)
#print(labels_1)

37652.659523809525


# 2 مع التعديلات

# MacQueen Algorithm 

In [1263]:
## MacQueen Algorithm ######

import numpy as np

#  Definition of function
def MacQueen_kmeans(data, k, max_iterations=50):

    # Randomly select initial cluster centers
    centers = data[np.random.choice(range(len(data)), k, replace=False)]

    # Definition of initial values
    labels= np.full(len(data), 999) 
    prev_centers = np.copy(centers)
    wss=0.0

    #Start repeating until there is no change in centers 
    for iter in range(max_iterations):
        # Assign each point to the nearest center
        for i in range(len(data)):
            point = data[i]
            distances = np.linalg.norm(point - centers, axis=1)
            cluster_index = np.argmin(distances)
            labels[i] = cluster_index
            
            # Updating cluster centers          
            for j in range(k):
                cluster_points = data[labels == j]
                if len(cluster_points) > 0:
                    centers[j] = cluster_points.mean(axis=0)
        # Check if cluster centers have changed
        if np.all(centers == prev_centers):
            break

        # Calculate "Within-Cluster Sum of Squares"
        distances = np.linalg.norm(data[:, np.newaxis] - centers, axis=2)    
        wss = np.sum(np.min(distances, axis=1)**2)
           
    return labels, centers, wss

In [1437]:
### MacQueen 
print("MacQueen Algorthim")
# قم بتحميل البيانات الخاصة بك
data =df7
#np.random.seed(55)
# تحديد عد العناقيد
k = 4


# تنفيذ خوارزمية K-means
labels, centers,wss= MacQueen_kmeans(data, k)
print("Labels:", labels)
#print("Centers:", centers)
print("wss:", wss)

MacQueen Algorthim
Labels: [0 2 3 2 1 2 2 1 2 3 0 0 0 0 3 0 0 0 3 1 0 0 1 0 2 2 3 2 3 2 3 3 2 2 1 3 3
 3 0 3 0 3 0]
wss: 96.0791978021978
